from os import getenv
from pyaudio import paInt24

# AUDIO
CHANNELS = 2
CHUNK = 1024
FORMAT = paInt24
RATE = 192000

# GPIO
BUTTON_RECORD = 33
BUTTON_RESET_SHUTDOWN = 32

LED_BLUE = 36
LED_GREEN = 35
LED_RED = 40
LED_YELLOW = 38

# SOCKET
API_KEY = getenv('TAPP_API_KEY')
HOST = getenv('TAPP_HOST')
SOCKET_PORT = getenv('TAPP_SOCKET_PORT')
